added instructions on ugprading
redpencilio/docker-virtuoso pull request #21
Opened 2023-08-31 08:53 UTC by nvdk

[view rendered README](https://github.com/redpencilio/docker-virtuoso/blob/087daa1f9e04a9d46d89cabd9e114fe17ef64c71/README.md#upgrading)

2023-11-22 14:05 UTC, erikap commented
Tried the upgrade guide and made some fixes. Can be merged imo @nvdk

2024-03-09 12:38 UTC, abeforgit commented on README.md
> +When upgrading it's recommend (and sometimes required!) to first dump to quads using the `dump_nquads` procedure:
```suggestion
When upgrading it's recommended (and sometimes required!) to first dump to quads using the `dump_nquads` procedure:
```

also: it doesn't make much sense to call it "recommended" here, as the described procedure further assumes you've made the dump. If there are cases where dumping quads is _not_ a good idea, then maybe mention those explicitly instead of saying "sometimes required"

2024-03-09 12:42 UTC, abeforgit commented on README.md
> +Consider truncating or removing the virtuoso.log file as well.
What's to consider? does the log file include important information for later debugging/investigation?
To me there can be 2 scenarios:
- the log file is important, and is normally backed up by our backup procedures. Thus, you should make sure to back it up before removing or risk losing information.
- the log file is transient, and is really only useful for rare cases container-specific debugging, but not for data forensics. Feel free to remove the file if it became big and everything seems to be running smoothly

2024-03-09 12:44 UTC, abeforgit commented on README.md
> +SQL> dump_nquads ('dumps', 1, 1000000000, 1);
I assume the 1000000000 is the amount of triples to be dumped, and is set to 1 trillion to basically say: "if you ever would have more triples than this, you have bigger problems". Might be nice to add a small note to that effect here.

2024-03-09 12:46 UTC, abeforgit commented on README.md
> +When this has completed move the dumps folder to the toLoad folder. Make sure to remove the following files:
```suggestion
When this has completed move the dumps folder to the toLoad folder (if it doesn't exist, create it under `data/db/toLoad`). Make sure to remove the following files:
```

2024-03-09 12:47 UTC, abeforgit commented on README.md
> +When this has completed move the dumps folder to the toLoad folder. Make sure to remove the following files:
(feel free to disregard suggestion if the folder is always created by virtuoso)

2024-03-09 12:49 UTC, abeforgit commented on README.md
> +docker compose stop virtuoso
why not `down`? won't we end up with an orphan container this way?

2024-03-09 12:59 UTC, abeforgit commented on README.md
> +When upgrading it's recommend (and sometimes required!) to first dump to quads using the `dump_nquads` procedure:
A more clear wording could be something like:
"We first dump to quads using the `dump_nquads` procedure. This allows the newly upgraded DB to optimize it's internals for the new data, which would not be possible if we'd restore from a backup."

2024-03-24 11:55 UTC, abeforgit requested changes

2024-03-24 11:55 UTC, abeforgit commented on README.md
> +mv data/db/dumps data/db/toLoad
from my experiments following this guide exactly on 1.2.0-rc.1, the automatic loading from the toLoad folder does **not** support nested dirs, so this command should be:

```suggestion
mv data/db/dumps/* data/db/toLoad
```

2024-03-24 13:36 UTC, abeforgit commented on README.md
> +mv data/db/dumps data/db/toLoad
note in some stacks, we have nq files committed to the repo, maybe a comment about how to deal with those would also be nice

2024-03-24 13:37 UTC, abeforgit commented on README.md
> +mv data/db/dumps data/db/toLoad
(suggestion: remove them before upgrading, and restore them after)

2024-03-26 09:19 UTC, nvdk commented on README.md
> +SQL> dump_nquads ('dumps', 1, 1000000000, 1);
it's not an issue if there's more, this is just the size the file is split at. This is documented in the linked page https://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFDumpNQuad

2024-03-26 09:21 UTC, nvdk commented on README.md
> +docker compose stop virtuoso
with stop you still have the container (and it's state) if necessary until you `up` the new container. so it seems the safer option. Up will replace the container, so no orphan unless you rename the container

2024-03-26 09:25 UTC, nvdk commented on README.md
> +Consider truncating or removing the virtuoso.log file as well.
the log is definitely valuable, but you can truncate to a reasonable length at this time. If you have years of logs you can easily truncate to a reasonable history. Some basic knowledge can be assumed in upgrade procedures in my opinion.

2024-03-26 09:26 UTC, merged